CREATE TABLE EMPLOYEE2 (
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(50),
	SALARY DECIMAL(10, 2) NOT NULL,
	JOINING_DATE DATE NOT NULL,
	AGE SMALLINT 
);

SELECT * FROM EMPLOYEE2;

-- Import data from csv file
-- method1  (using excel)

COPY 
employee2 (employee_id	,first_name	,last_name	,email	,department	,salary,	joining_date	,age
) FROM 'C:\react_pro\sql\basic_postgre\ST - SQL ALL PRACTICE FILES SD61\ST - SQL ALL PRACTICE FILES-2\All Excel Practice Files\employee_data.csv'
DELIMITER ','
CSV HEADER;


SELECT * FROM EMPLOYEE2;

-- method 2 ( using import / export)

CREATE TABLE EMPLOYEE3 (
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(50),
	SALARY DECIMAL(10, 2) NOT NULL,
	JOINING_DATE DATE NOT NULL,
	AGE SMALLINT 
);
SELECT * FROM EMPLOYEE3;
