CREATE TABLE EMPLOYEE2 (
	EMPLOYEE_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(50),
	SALARY DECIMAL(10, 2) NOT NULL,
	JOINING_DATE DATE NOT NULL,
	AGE SMALLINT ,
);